cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<slug:slug>/', views.cart_add, name='cart_add'),
    path('remove/<slug:slug>', views.cart_remove, name='cart_remove'),
    path('checkout', views.cart_checkout, name='cart_checkout'),
]

udemyclone/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from udemyclone import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('', include('accounts.urls')),
    path('', include('udemy.urls')),
    path('', include('courses.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]


class CartAddCourseForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.decorators.http import require_POST

from courses.models import Course
from udemy.models import Enroll
from .cart import Cart


@require_POST
def cart_add(request, slug):
    cart = Cart(request)  # create a new cart object passing it the request object
    course = get_object_or_404(Course, slug=slug)
    cart.add(course=course, quantity=1, update_quantity=False)
    return redirect('cart:cart_detail')


def cart_remove(request, slug):
    cart = Cart(request)
    course = get_object_or_404(Course, slug=slug)
    cart.remove(course)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})


@login_required(login_url='/login')
def cart_checkout(request):
    carts = Cart(request)
    for cart in carts:
        course = cart['course']
        # course = get_object_or_404(Course, slug=course.slug)
        Enroll.objects.create(course=course, user_id=request.user.id)
    messages.success(request, 'Successfully checked out!')
    carts.clear()
    return redirect(reverse_lazy('cart:cart_detail'))

templates/cart/detail.html
{% extends 'layouts/base.html' %}

{% load static %}
{% load humanize %}

{% block content %}

    <section class="page-header-area">
        <div class="container">
            <div class="row">
                <div class="col">
                    <nav>
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="/">
                                    <i class="fas fa-home"></i>
                                </a>
                            </li>
                            <li class="breadcrumb-item"><a href="#">Shopping Cart</a></li>
                        </ol>
                    </nav>
                    <h1 class="page-title">Shopping Cart</h1>
                </div>
            </div>
        </div>
    </section>


    <section class="cart-list-area">
        <div class="container">
            {% with total_items=cart|length %}
                {% if cart|length > 0 %}
                    <div class="row" id="cart_items_details">
                        <div class="col-lg-9">

                            <div class="in-cart-box">
                                <div class="title">{{ total_items }} courses in cart</div>
                                <div class="">
                                    <ul class="cart-course-list">
                                        {% for item in cart %}
                                            {% with course=item.course %}
                                                <li>
                                                    <div class="cart-course-wrapper">
                                                        <div class="image">
                                                            <a href="">
                                                                <img src="{% static 'images/learning.jpg' %}" alt=""
                                                                     class="img-fluid">
                                                            </a>
                                                        </div>
                                                        <div class="details">
                                                            <a href="">
                                                                <div class="name">{{ course.title }}</div>
                                                            </a>
                                                        </div>
                                                        <div class="move-remove">
                                                            <div>
                                                                <form action="" method="post">
                                                                    {% csrf_token %}
                                                                    <input type="hidden" value="{{ course.slug }}">
                                                                    <input type="submit" class="btn-success"
                                                                           value="Remove">
                                                                </form>
                                                            </div>
                                                            <!-- <div>Move to Wishlist</div> -->
                                                        </div>
                                                        <div class="price">
                                                            <a href="">
                                                                <div class="current-price">
                                                                    ${{ course.price | floatformat:2 | intcomma }}
                                                                </div>
                                                                <span class="coupon-tag">
                                                                    <i class="fas fa-tag"></i>
                                                                </span>
                                                            </a>
                                                        </div>
                                                    </div>
                                                </li>
                                            {% endwith %}
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="cart-sidebar">
                                <div class="total">Total:</div>
                                <div class="total-price">
                                    $<span id="total_price_of_checking_out">{{ cart.get_total_price | floatformat:2 | intcomma }}</span>
                                </div>
                                <a href="{% url "cart:cart_checkout" %}" class="btn btn-primary btn-block checkout-btn">Checkout
                                </a>
                            </div>
                        </div>
                    </div>
                {% else %}
                    <div class="title">Cart is empty</div>
                {% endif %}
            {% endwith %}
        </div>
    </section>

{% endblock %}