accounts/urls.py
from django.urls import path, include

from . import views

app_name = 'accounts'

urlpatterns = [
    path('login', views.LoginView.as_view(), name='login'),
    path('register', views.RegisterView.as_view(), name='register'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('users/', include([
        path('my-courses', views.EnrolledCoursesListView.as_view(), name='enrolled-courses'),
        path('my-courses/<slug:slug>/view', views.StartLessonView.as_view(), name='course-lessons'),
        path('my-courses/<slug:slug>/lessons/<int:id>', views.LessonView.as_view(), name='course-lessons-single'),
        path('profile', views.ProfileUpdateView.as_view(), name='my-profile'),
    ])),
]

cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<slug:slug>/', views.cart_add, name='cart_add'),
    path('remove/<slug:slug>', views.cart_remove, name='cart_remove'),
    path('checkout', views.cart_checkout, name='cart_checkout'),
]

udemyclone/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from udemyclone import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('', include('accounts.urls')),
    path('', include('udemy.urls')),
    path('', include('courses.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/lessons/lessons_by_course.html
{% extends 'layouts/base.html' %}

{% block content %}

    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-3">
                <div class="accordion" id="accordionExample">
                    <div class="card" style="margin:10px 0;">

                        <div id="" class="collapse show"
                             aria-labelledby="" data-parent="#accordionExample">
                            <div class="card-body" style="padding:0;">
                                <table style="width: 100%;">

                                    {% for lesson in lessons %}

                                        <tr style="width: 100%; padding: 5px 0px;">
                                            <td style="text-align: left;padding:10px; border-bottom:1px solid #ccc;">
                                                <a href="{% url 'accounts:course-lessons-single' slug=course.slug id=lesson.id %}"
                                                   id="{{ lesson.id }}">
                                                    <i class="fa fa-play"
                                                       style="font-size: 12px;color: #909090;padding: 10px;"></i>
                                                    {{ lesson.title }}
                                                </a>
                                            </td>
                                            <td style="text-align: right; padding:10px; border-bottom:1px solid #ccc;">
                                                <span class="lesson_duration">
                                                    {{ lesson.duration | floatformat:2 }}
                                                </span>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-9" id="video_player_area">
                <div class="" style="background-color: #333;">
                    <div class="embed-responsive embed-responsive-16by9">
                        <iframe width="100%" height="500" class="embed-responsive-item"
                                src="https://www.youtube.com/embed/Kyx2PsuwomE" frameborder="0"
                                allowfullscreen>
                        </iframe>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}